name: unit tests

on:
  push:
    # branches: [ "main" ]
  pull_request:
    # branches: [ "main" ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [macos-latest]
    # runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: make build
      run: make build
      
    - name: make test
      run: make test/junit

    - name: Report test results
      uses: dorny/test-reporter@v2
      if: ${{ !cancelled() }}       # run this step even if previous step failed
      with:
        name: unit Tests            # Name of the check run which will be created
        path: junit.xml    # Path to test results
        reporter: java-junit        # Format of test results

    - name: ⚙️ Install lcov
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get -y install lcov

    - name: coverage.info
      if: runner.os == 'Linux'
      run: make coverage/info

    - name: Upload coverage to Codecov
      if: runner.os == 'Linux'
      uses: codecov/codecov-action@v5
      with:
        files: .coverage/coverage.info
        flags: unittests
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
  
