name: unit tests

on:
  push:
    # branches: [ "main" ]
  pull_request:
    # branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make build
      run: make build
    - name: make test
      run: make test/junit

    - name: Report test results
      uses: dorny/test-reporter@v2
      if: ${{ !cancelled() }}       # run this step even if previous step failed
      with:
        name: unit Tests            # Name of the check run which will be created
        path: junit.xml    # Path to test results
        reporter: java-junit        # Format of test results

    - name: ⚙️ Install lcov
      run: |
        sudo apt-get update
        sudo apt-get -y install lcov

    - name: coverage.info
      run: make coverage/info

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: .coverage/coverage.info
        flags: unittests
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
  
